<FDLabel>:
	orientation: 'horizontal'
	size_hint: 1, None
	height: dp(50)

	MDLabel:
		size_hint: .4, 1
		text: f'{root.title.capitalize()}:'

	MDLabel:
		size_hint: .6, 1
		text: root.value


<FDLabelTwoLine>:
	orientation: 'vertical'
	size_hint: 1, None
	height: dp(60)

	MDLabel:
		size_hint: 1, .3
		text: f'{root.title.capitalize()}:'
		font_style: 'Caption'
		theme_text_color: 'Custom'
		text_color: .3, .3, .3, 1

	MDLabel:
		size_hint: 1, .7
		text: root.value