#:import FDInput ui.fields.input
#:import FDSwitch ui.fields.switch
#:import FDSelect ui.fields.select


<EmergencyModelContent>:
	orientation: 'vertical'
	size_hint_y: None

	FDInput:
		id: title
		hint_text: 'Название'

	MDTextField:
		id: description
		hint_text: 'Описание'
		multiline: True

	FDSwitch:
		id: urgent
		icon: ''
		title: 'Срочный'

	FDSelect:
		id: tags
		icon: 'pound'
		title: 'Теги'

	FDSelect:
		id: humans
		icon: 'account-group'
		title: 'Люди'