<FDColor>:
	orientation: 'horizontal'
	size_hint: 1, None
	size: self.width, 50

	MDBoxLayout:
		id: label

		MDIcon:
			size_hint: None, 1
			size: self.height, self.height
			icon: root.icon

		MDLabel:
			size_hint: 1, 1
			text: root.display_text

	MDFloatingActionButton:
		id: button
		size_hint: None, None
		size: 50, 50
		icon: 'palette'
		md_bg_color: 1.0, 1.0, 1.0, 1.0

		on_release:
			root.color_dialog.open()