#:import Settings settings.settings

<AbstractPage>
	MDBoxLayout:
		orientation: 'vertical'

		MDToolbar:
			left_action_items:
				[['arrow-left', lambda x: app.root.move_to_back(x)]]
			md_bg_color: Settings.BACKGROUND_COLOR_OPACITY
			specific_text_color: Settings.FONT_COLOR
			elevation: 10
			id: toolbar

		ScrollView:
			GridLayout:
				cols: 1
				height: self.minimum_height
				size_hint: 1, None
				do_scroll_x: False
				spacing: 10
				padding: [20, 10]
				id: container