<TopPanelTab>:
	size_hint: None, 1
	width: dp(175)
	orientation: 'horizontal'

	MDFlatButton:
		text: root.title
		text_size: root.size
		size_hint: 1, 1

	MDIconButton:
		icon: 'close'
		size_hint: None, None
		size: dp(50), dp(50)


<TopPanel>:
	size_hint: 1, None
	height: dp(50)

	ScrollView:
		GridLayout:
			id: tabs_container
			rows: 1
			size_hint: None, 1
			width: self.minimum_width
			do_scroll_y: False
			spacing: dp(10), 0