#:import FDIcon,FDLabel app.tools.custom_widgets.label


<SelectField>:
	size_hint: 1, None
	size: self.width, 100
	orientation: 'vertical'

	MDBoxLayout:
		size_hint: 1, None
		size: self.width, 50

		MDIcon:
			size_hint: None, None
			size: 50, 50
			icon: root.icon

		MDLabel:
			text: root.display_text

	MDBoxLayout:
		size_hint: 1, None
		size: self.width, 50

		MDRectangleFlatButton:
			text: 'MDRectangleFlatButton'