<CallTabContent>:
	orientation: 'vertical'

	MDBottomNavigation:
		# panel_color: app.theme_cls.primary_color

		MDBottomNavigationItem:
			name: 'calls'
			text: 'Вызовы'
			icon: 'phone'

			MDBoxLayout:
				id: calls
				orientation: 'vertical'
				size_hint: (1, 1)

		MDBottomNavigationItem:
			name: 'info'
			text: 'Информация'
			icon: 'fire'

			MDBoxLayout:
				id: info
				orientation: 'vertical'
				size_hint: (1, 1)
