<BaseScreen>:
	canvas:
		Color:
			rgba: root.color
		Rectangle:
			pos: root.pos
			size: root.size
			source: root.bg_image

	MDBoxLayout:
		id: widgets
		orientation: 'vertical'


<FDBottomNavigation>:
	MDBottomNavigation:
		id: nav

		MDBottomNavigationItem:
			name: 'screem_1'
			text: 'Text 1'
			icon: 'account'

			MDLabel:
				text: 'Screen 1'

		MDBottomNavigationItem:
			name: 'screen_2'
			text: 'Text 2'
			icon: 'bus'

			MDLabel:
				text: 'Screen 2'