<_ModelListElementContent>:
	orientation: 'horizontal'
	size_hint: (1, None)
	height: dp(50)
	spacing: dp(10)
	padding: [0, dp(10)]

	MDRectangleFlatIconButton:
		id: edit_btn
		size_hint: (None, None)
		size: root.width // 2 - dp(5), dp(30)
		icon: 'file-edit'
		text: 'Редактировать'

	MDRectangleFlatIconButton:
		id: info_btn
		size_hint: (None, None)
		size: root.width // 2 - dp(5), dp(30)
		icon: 'information'
		text: 'Информация'