<ListElement>:
	on_release:
		# app.forward(self.to_edit_screen)
		print('ListElement is pressed')


<AbstractUpdateListScreen>:
	MDBoxLayout:
		orientation: 'vertical'

		MDToolbar:
			id: toolbar
			left_action_items: [['arrow-left', lambda x: app.back(), '']]
			right_action_items: [['delete', lambda x: print(x), 'Select to delete']]
			elevation: 10

		ScrollView:
			MDSelectionList:
				id: content
				padding: [20, 10]
				spacing: 10