<ListElement>:
	size_hint: 1, None
	size: self.width, 50
	on_press:
		app.forward(self.to_edit_screen)


<AbstractUpdateListScreen>:
	MDBoxLayout:
		orientation: 'vertical'

		MDToolbar:
			id: toolbar
			left_action_items: [['arrow-left', lambda x: app.back(), '']]
			elevation: 10

		ScrollView:
			GridLayout:
				id: content
				cols: 1
				do_scroll_x: False
				size_hint: 1, None
				height: self.minimum_height
				padding: [20, 10]
				spacing: 10