<ListElement>:
	on_release:
		app.forward(self.to_edit_screen)
		app.root.current_screen.update_content(self._element)


<SelectionList>:
	padding: [20, 10]
	spacing: 10


<AbstractUpdateListScreen>:
	MDBoxLayout:
		orientation: 'vertical'

		MDToolbar:
			id: toolbar
			left_action_items: [['arrow-left', lambda x: app.back(), '']]
			elevation: 10

		ScrollView:
			List:
				id: content
				padding: [20, 10]
				spacing: 10