<ElementContent>:
	orientation: 'horizontal'
	size_hint: 1, None
	size: self.width, 50
	padding: [30, 0]

	MDBoxLayout:
		orientation: 'horizontal'
		id: content
		spacing: 0

	MDIconButton:
		id: view_button
		size_hint: None, None
		size: 50, 50
		icon: 'eye'

		# on_release:
		# 	# root.path_manager.forward('fires')
		# 	app.screen_manager.get_screen(app.screen_manager.current).path_manager_.forward('fires')